# Generated by Django 4.0.3 on 2022-03-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_experience_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('university_name', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
