# Generated by Django 4.0.3 on 2022-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
